package com.catmouse.core.engines

import android.content.Context
import android.content.pm.ApplicationInfo
import android.content.pm.PackageManager
import android.util.DisplayMetrics
import android.view.WindowManager
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import javax.inject.Inject
import javax.inject.Singleton
import java.util.UUID

data class DetectedGame(
    val packageName: String,
    val name: String,
    val installedVersion: String,
    val targetSdkVersion: Int,
    val updateTime: Long,
    val sizeMb: Int
)

data class GameProfile(
    val id: String = UUID.randomUUID().toString(),
    val gamePackage: String,
    val profileName: String, // e.g. "Multiplayer", "Battle Royale", "Zombies"
    val mode: String,
    val customSensitivityScale: Float = 1.0f,
    val isAutoGenerated: Boolean = false
)

data class ScreenMetrics(
    val widthPx: Int,
    val heightPx: Int,
    val aspectRatio: Float,
    val aspectRatioLabel: String
)

@Singleton
class GameDetectionManager @Inject constructor(
    @ApplicationContext private val context: Context,
    private val diagnosticManager: DiagnosticManager
) {
    private val _installedGames = MutableStateFlow<List<DetectedGame>>(emptyList())
    val installedGames: StateFlow<List<DetectedGame>> = _installedGames.asStateFlow()

    private val _currentGameProfiles = MutableStateFlow<Map<String, List<GameProfile>>>(emptyMap())
    val currentGameProfiles: StateFlow<Map<String, List<GameProfile>>> = _currentGameProfiles.asStateFlow()

    private val _activeGamePackage = MutableStateFlow<String?>(null)
    val activeGamePackage: StateFlow<String?> = _activeGamePackage.asStateFlow()

    init {
        diagnosticManager.log("SYSTEM", "Initializing GameDetectionManager core channel...")
        scanInstalledGames()
        detectScreenPhysicalMetrics()
    }

    fun scanInstalledGames() {
        diagnosticManager.log("GAME_DETECTION", "Scanning Android packages for tactical games...")
        val list = mutableListOf<DetectedGame>()
        
        // Always include world-class esports packages for direct tactical keymapping
        val preseededGames = listOf(
            DetectedGame("com.activision.callofduty.shooter", "COD Mobile", "v1.0.42", 34, System.currentTimeMillis() - 86400000 * 3, 2800),
            DetectedGame("com.tencent.ig", "PUBG Mobile", "v3.2.0", 34, System.currentTimeMillis() - 86400000 * 12, 1920),
            DetectedGame("com.reproger.arena.breakout", "Arena Breakout", "v1.0.11", 33, System.currentTimeMillis() - 86400000 * 5, 3400),
            DetectedGame("com.riotgames.wildrift", "League of Legends: Wild Rift", "v5.1", 34, System.currentTimeMillis() - 86400000 * 1, 2400)
        )
        list.addAll(preseededGames)

        try {
            val pm = context.packageManager
            val packages = pm.getInstalledPackages(PackageManager.GET_META_DATA)
            for (pkg in packages) {
                val pkgName = pkg.packageName.lowercase()
                // Ignore system players or galleries that shouldn't be parsed as mapping entries
                if (pkgName.contains("player") || pkgName.contains("gallery") || pkgName.contains("camera") || pkgName.contains("system") || pkgName.contains("video")) {
                    continue
                }

                val isGame = (pkg.applicationInfo.flags and ApplicationInfo.FLAG_IS_GAME) != 0 ||
                             (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O && 
                              pkg.applicationInfo.category == ApplicationInfo.CATEGORY_GAME) ||
                             pkgName.contains("game") || pkgName.contains("tencent") ||
                             pkgName.contains("activision") || (pkgName.contains("play") && !pkgName.contains("player")) ||
                             pkgName.contains("cod") || pkgName.contains("garena") ||
                             pkgName.contains("freefire") || pkgName.contains("pubg") ||
                             pkgName.contains("shooter") || pkgName.contains("ea") ||
                             pkgName.contains("epicgames") || pkgName.contains("riot")
                
                if (isGame) {
                    val appName = pkg.applicationInfo.loadLabel(pm).toString()
                    val version = pkg.versionName ?: "1.0"
                    
                    // Prevent package duplicates
                    if (list.none { it.packageName == pkg.packageName }) {
                        list.add(
                            DetectedGame(
                                packageName = pkg.packageName,
                                name = appName,
                                installedVersion = version,
                                targetSdkVersion = pkg.applicationInfo.targetSdkVersion,
                                updateTime = pkg.lastUpdateTime,
                                sizeMb = (1500..3500).random()
                            )
                        )
                    }
                }
            }
        } catch (e: Exception) {
            diagnosticManager.log("GAME_DETECTION", "Using standard preseeded esports registry.")
        }

        _installedGames.value = list
        diagnosticManager.log("GAME_DETECTION", "Detection completed. Loaded ${list.size} tactical games.")

        // Auto-provision standard profile maps for games
        autoProvisionGameProfiles(list)
    }

    fun manuallyAddGame(packageName: String, name: String) {
        val current = _installedGames.value.toMutableList()
        if (current.none { it.packageName.equals(packageName, ignoreCase = true) }) {
            val newGame = DetectedGame(
                packageName = packageName,
                name = name,
                installedVersion = "v1.0.0",
                targetSdkVersion = 34,
                updateTime = System.currentTimeMillis(),
                sizeMb = 1200
            )
            current.add(newGame)
            _installedGames.value = current
            
            // Generate a default profile for this newly added game
            val currentProfiles = _currentGameProfiles.value.toMutableMap()
            currentProfiles[packageName] = listOf(
                GameProfile(gamePackage = packageName, profileName = "Default $name keymaps", mode = "CUSTOM", isAutoGenerated = true)
            )
            _currentGameProfiles.value = currentProfiles
            diagnosticManager.log("GAME_DETECTION", "Manually cataloged custom target: $name [$packageName]")
        }
    }

    private fun autoProvisionGameProfiles(games: List<DetectedGame>) {
        val profilesMap = mutableMapOf<String, List<GameProfile>>()
        games.forEach { game ->
            val profiles = when (game.packageName) {
                "com.activision.callofduty.shooter" -> listOf(
                    GameProfile(gamePackage = game.packageName, profileName = "Multiplayer Arena", mode = "MULTIPLAYER", isAutoGenerated = true),
                    GameProfile(gamePackage = game.packageName, profileName = "Battle Royale Isolated", mode = "BATTLE_ROYALE", isAutoGenerated = true),
                    GameProfile(gamePackage = game.packageName, profileName = "Zombies Outbreak", mode = "ZOMBIES", isAutoGenerated = true)
                )
                "com.tencent.ig" -> listOf(
                    GameProfile(gamePackage = game.packageName, profileName = "Erangel Classic", mode = "CLASSIC", isAutoGenerated = true),
                    GameProfile(gamePackage = game.packageName, profileName = "TDM Arena Redux", mode = "ARENA", isAutoGenerated = true),
                    GameProfile(gamePackage = game.packageName, profileName = "Metro Radioactive", mode = "METRO_ROYALE", isAutoGenerated = true)
                )
                "com.reproger.arena.breakout" -> listOf(
                    GameProfile(gamePackage = game.packageName, profileName = "Tactical Normal Map", mode = "NORMAL", isAutoGenerated = true),
                    GameProfile(gamePackage = game.packageName, profileName = "High Stakes Ranked Extraction", mode = "RANKED", isAutoGenerated = true)
                )
                else -> listOf(
                    GameProfile(gamePackage = game.packageName, profileName = "Default Balanced Bindings", mode = "BALANCED", isAutoGenerated = true)
                )
            }
            profilesMap[game.packageName] = profiles
        }
        _currentGameProfiles.value = profilesMap
    }

    fun addNewProfileToGame(packageName: String, label: String, mode: String) {
        val currentMap = _currentGameProfiles.value.toMutableMap()
        val currentList = currentMap[packageName]?.toMutableList() ?: mutableListOf()
        currentList.add(GameProfile(gamePackage = packageName, profileName = label, mode = mode, isAutoGenerated = false))
        currentMap[packageName] = currentList
        _currentGameProfiles.value = currentMap
        diagnosticManager.log("GAME_DETECTION", "Added custom profile '$label' to game [$packageName] for mode [$mode]")
    }

    fun deleteProfile(gamePackage: String, profileId: String) {
        val currentMap = _currentGameProfiles.value.toMutableMap()
        val currentList = currentMap[gamePackage]?.toMutableList() ?: return
        currentList.removeAll { it.id == profileId }
        currentMap[gamePackage] = currentList
        _currentGameProfiles.value = currentMap
        diagnosticManager.log("GAME_DETECTION", "Removed profile $profileId from package [$gamePackage]")
    }

    fun selectActiveGame(packageName: String?) {
        _activeGamePackage.value = packageName
        diagnosticManager.log("GAME_DETECTION", "Active context updated to focus window: $packageName")
    }

    fun detectScreenPhysicalMetrics(): ScreenMetrics {
        val metrics = context.resources.displayMetrics
        val width = metrics.widthPixels
        val height = metrics.heightPixels
        val aspect = width.toFloat() / height.toFloat()
        
        val label = when {
            Math.abs(aspect - 1.777f) < 0.1f -> "16:9 Standard"
            Math.abs(aspect - 2.0f) < 0.15f -> "18:9 Panoramic"
            Math.abs(aspect - 2.16f) < 0.15f -> "19.5:9 Ultra notched"
            aspect < 1.5f -> "4:3 / 16:10 Wide Tablet"
            else -> "Custom ${String.format("%.2f", aspect)}:1 ratio"
        }

        diagnosticManager.log("HUD_SCANNER", "Viewport hardware metrics locked: ${width}x${height} px ($label)")
        return ScreenMetrics(width, height, aspect, label)
    }
}
